name: json_to_flutter
description: A package to convert JSON files to Flutter code.
version: 1.1.0
repository: https://github.com/Thiago-Rizzo/json_to_flutter
homepage: https://github.com/Thiago-Rizzo/json_to_flutter

environment:
  sdk: ^3.7.0

dependencies:
  change_case: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  jf: json_to_flutter
